import { IdeaFeedItem } from "./types";

export const mockIdeas: IdeaFeedItem[] = [
  // Content ideas first — strongest "wow" category
  {
    id: "explain-anything-simply",
    title: "Turn Complex Ideas Into Simple, Viral Content",
    subtext: "Make posts people actually understand and share",
    moneyTag: "$$",
    effortTag: "Low",
  },
  {
    id: "lesson-to-linkedin-post",
    title: "Turn One Lesson Into a LinkedIn Post",
    subtext: "Write a post from something you learned this week",
    moneyTag: "$$",
    effortTag: "Low",
  },
  {
    id: "cold-outreach-message-generator",
    title: "Your Cold Messages Are Getting Ignored — Fix That",
    subtext: "Generate outreach that actually gets replies",
    moneyTag: "$$",
    effortTag: "Low",
  },
  {
    id: "opinion-to-viral-thread",
    title: "Turn One Opinion Into a Thread People Share",
    subtext: "Structure a hot take into content that spreads",
    moneyTag: "$$",
    effortTag: "Low",
  },
  {
    id: "rent-affordability-reality-check",
    title: "You're Probably Overpaying Rent — Check in 60 Seconds",
    subtext: "Calculate what you can actually afford after expenses",
    moneyTag: "$$",
    effortTag: "Low",
  },
  {
    id: "property-deal-roi-quick-analyzer",
    title: "Is This Property Deal Actually Worth It?",
    subtext: "Quickly estimate ROI without spreadsheets",
    moneyTag: "$$$",
    effortTag: "Medium",
  },
  {
    id: "subscription-leak-finder",
    title: "You're Leaking Money Every Month Without Realising",
    subtext: "Find subscriptions you should cancel instantly",
    moneyTag: "$$",
    effortTag: "Low",
  },
  {
    id: "underserved-niche-finder",
    title: "Find Underserved Niches Before Everyone Else",
    subtext: "Spot opportunities with low competition",
    moneyTag: "$$$",
    effortTag: "Medium",
  },
  {
    id: "problem-to-business-idea-converter",
    title: "Turn Any Problem Into a Business Idea",
    subtext: "Convert pain points into real opportunities",
    moneyTag: "$$",
    effortTag: "Low",
  },
  {
    id: "would-you-take-this-trade",
    title: "Would You Have Taken This Trade?",
    subtext: "Test your instincts before risking real money",
    moneyTag: "$$$",
    effortTag: "Medium",
  },
  {
    id: "validate-before-you-waste-time",
    title: "This Side Hustle Looks Good — But Will It Actually Work?",
    subtext: "Validate any idea before wasting time",
    moneyTag: "$$$",
    effortTag: "Low",
  },
  {
    id: "build-a-simple-tool",
    title: "Build a Simple Tool People Would Actually Pay For",
    subtext: "Get a micro-tool idea you can launch fast",
    moneyTag: "$$$",
    effortTag: "Medium",
  },
  {
    id: "steal-proven-business-ideas-smarter",
    title: "Steal Proven Business Ideas (But Do It Smarter)",
    subtext: "Find what's working and improve it",
    moneyTag: "$$",
    effortTag: "Medium",
  },
  {
    id: "turn-skills-into-digital-product",
    title: "Turn Your Skills Into a Digital Product",
    subtext: "Find something you can sell online quickly",
    moneyTag: "$$",
    effortTag: "Medium",
  },
  {
    id: "hidden-money-in-your-industry",
    title: "Find Hidden Ways to Make Money in Your Industry",
    subtext: "Opportunities most people overlook",
    moneyTag: "$$$",
    effortTag: "Medium",
  },
];
